---
name: Module-Build-Kwalitee
version: 0.22
author:
  - |-
    Stig Brautaset <stig@brautaset.org>,
    Mark Fowler <mark@twoshortplanks.com>,
    Norman Nunley <nnunley@fotango.com>,
    Chia-liang Kao <clkao@clkao.org>,
    et al.
abstract: Module::Build subclass with prepackaged tests
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Find::Rule: 0
  Module::Build: 0.2609
  Test::More: 0
  Test::Pod: 0
  YAML: 0
recommends:
  IPC::Open3: 0
  Pod::Coverage::CountParents: 0
provides:
  Module::Build::Kwalitee:
    file: lib/Module/Build/Kwalitee.pm
    version: 0.22
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
