--- #YAML:1.0
name: Module-Build-Kwalitee
version: 0.24
author:
  - Stig Brautaset <stig@brautaset.org>,
Mark Fowler <mark@twoshortplanks.com>,
Norman Nunley <nnunley@fotango.com>,
Chia-liang Kao <clkao@clkao.org>,
et al.
abstract: Module::Build subclass with prepackaged tests
license: perl
generated_by: Module::Build version 0.2609, without YAML.pm
